ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

CREATE USER IDARI IDENTIFIED BY "dbhunter"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT DBA TO IDARI;
  ALTER USER IDARI DEFAULT ROLE ALL;
  ALTER USER IDARI QUOTA UNLIMITED ON USERS;
  GRANT CREATE ROLE TO IDARI;
  GRANT CREATE USER TO IDARI;
  GRANT CREATE SESSION TO IDARI;
